version: '3'

tasks:
  proto-build:
    cmds:
      - protoc --go_out=grpc --proto_path=grpc --go_opt=paths=source_relative --php_out=grpc/php/src --go-grpc_out=grpc --go-grpc_opt=paths=source_relative $(find grpc -iname "*.proto")
    silent: true