on:
  create:
    tags:
      - 'v*'

name: 🏗️✨ Build Workflow

jobs:
  Build:
    name: 🖥️ 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛡️ 🔒 Add Siteworx CA Certificates
        run: |
          apt update && apt install -yq ca-certificates curl
          curl -Ls https://siteworxpro.com/hosted/Siteworx+Root+CA.pem -o /usr/local/share/ca-certificates/sw.crt
          update-ca-certificates

      - name: 📖 🔍 Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: 🔑 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏗️ 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Replace entrypoint
        run: |
          sed -i 's/server/grpc/g' Dockerfile      

      - name: 🐳 🔨 Build Grpc Container
        uses: docker/build-push-action@v6
        with:
          sbom: true
          provenance: true
          platforms: linux/arm64,linux/amd64
          context: .
          dockerfile: Dockerfile
          push: true
          tags: siteworxpro/img-proxy-url-generator:${{ gitea.ref_name }}-grpc